### ISSUE TITLE
ami20190217_status_on_Linux

### ISSUE THREAD

**Issue by vinitamehlawat** [petermr/tigr2ess#46]
Sir 

Using `getpapers` i tried `getpapers -q 'ocimum tenuiflorum' -o ocimumten_xml  -x -k 100` and get result files in folder `ocimumten_xml`
i run `ami-search-cooccur  ocimumten_xml/ gene plantparts country species drugs
I got stuck there by 2 points:
   *It takes Much time more than 30 min and i quite this job in between*
    *I got many files as in previous one  ami-jar But using new jar(20190217) i got one new file that is species.binomial.document.xml (same for gene ,plantparts,country) & Did not get cooccur folder in my ocimumten_xml folder.*

1.This is command i use in this image and  i forcefully quite this after 30 min.

![ami_search_command](https://user-images.githubusercontent.com/47384975/52944070-95a05580-3394-11e9-8f58-7b5ba392206a.png)

2.Here i am attaching image of error shown when i only use plantarts country  and gene in ami-search-cooccur

![ami_search_error](https://user-images.githubusercontent.com/47384975/52944080-9b963680-3394-11e9-83c7-831de683bf9b.png)

please  correct me if i am doing something wrong with this new ami-jar commands or something else

**Comment by petermr** [comment]
Thank you, this is an excellent report. 
(It is better to include the actual output as text rather than a screenshot as I can cut and paste).


I think the problem is that some papers are very large and contain large numbers of species or genes. I will try to add a commandline switch that aborts papers which are too large. I will run the same job, and try to trap the problem.

It is not your fault - it's a bug.

Well done.
