### ISSUE TITLE
"Test run of ami-search-cooccur for the new release of ami20190219b."

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#67]
##### Run time log
```
ambarish123@ubuntu:~$ ami-search-cooccur ricenew/ country gene drugs
*******************************
WARNING: AMISearch is being replaced by AMISearchTool (ami-search-new)
*******************************

1    [main] DEBUG org.contentmine.ami.AMIProcessor  - project name: ricenew/ /home/ambarish123

running: word; word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]...
running: search; search([country])[]...
running: gene; gene([human])[]47800 [main] DEBUG org.contentmine.ami.dictionary.gene.HGNCDictionary  - is /org/contentmine/ami/plugins/gene/hgnc/hgnc.xml
...
running: search; search([drugs])[]...
create data tables
Exception in thread "main" java.lang.RuntimeException: Null metadataByTreename
	at org.contentmine.cproject.util.DataTablesTool.setMetadataByTreename(DataTablesTool.java:501)
	at org.contentmine.ami.plugins.CommandProcessor.createDataTables(CommandProcessor.java:212)
	at org.contentmine.ami.AMIProcessor.runSearches(AMIProcessor.java:118)
	at org.contentmine.ami.AMIProcessor.runSearchesAndCooccurrence(AMIProcessor.java:193)
	at org.contentmine.ami.tools.AMISearch.runAMISearches(AMISearch.java:51)
	at org.contentmine.ami.tools.AMISearch.main(AMISearch.java:32)
```

**Comment by petermr** [comment]
The error message specifically says that you should no longer use

On Wed, Feb 20, 2019 at 6:49 AM Ambarish Kumar <notifications@github.com>
wrote:

> Status of the test run of the ami-search-cooccur for the new release of
> the ami20190219b is not successful.

That's because it has been superseded.

Error is of run time exception related of not finding metadata file (most
> probably generated from eupmc_results.json containing bibliographic
> information). Failed to find all cooccurrences among specified search
> terms. Run time log
>
> ambarish123@ubuntu:~$ ami-search-cooccur ricenew/ country gene drugs
> *******************************
> WARNING: AMISearch is being replaced by AMISearchTool (ami-search-new)
> *******************************
>
> ^^^
Is this message unclear? If so I will strengthen it.




-- 
Peter Murray-Rust
Reader Emeritus in Molecular Informatics
Unilever Centre, Dept. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069
